#!/usr/bin/env python
"""Appendix C tables (LaTeX, booktabs) from the Chapter 6 result files. Local, CPU only.

Writes three tables into thesis/tables/:
  vae_test.tex  VAE reconstruction on the standalone 256x256 test.h5 (500 sims):
                pooled VRMSE, channel-mean VRMSE +- SEM, delta vs. the baseline,
                per-channel VRMSE. Source: <run>/test_eval_256.json.
  vae_val.tex   the same arms on the 500-sim validation split, at the checkpoint
                with the best val_vrmse (always epoch 20 here). Source:
                <run>/metrics/metrics.csv. Shows that test and val agree.
  dit.tex       VAE-only vs VAE+DiT on test.h5 per DiT arm. Source:
                logs/sng_pvc/eval_dit_vrmse/<job>/vrmse_summary.json; for each
                arm the NEWEST 500-sim test-split eval is used, so a rerun
                supersedes older evals automatically. The job ids used are
                printed; check them.

SEMs are over the 500 per-sim values. Deltas are relative to the baseline's
channel-mean VRMSE. Rerun after new results land:
    python scripts/thesis_tables.py
"""

import csv
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "thesis" / "tables"
CH = ["density", "momentum_x", "momentum_y", "pressure"]
BASELINE = "loss_rmse_h1_256res"

# (run folder minus finetune_vae_ch6_, cluster mirror, group, label), table order
VAE_ARMS = [
    ("unfinetuned_256res", "sng_pvc", "Adaptation", "Unfinetuned (inflated only)"),
    ("color_adapter_nossim_256res", "sng_pvc", "Adaptation", "Colour adapter"),
    ("decoder_only_nossim_256res", "sng_pvc", "Adaptation", "Decoder only"),
    ("conv_in_only_256res", "jupiter", "Adaptation", "Decoder + conv\\_in"),
    ("loss_rmse_h1_256res", "sng_pvc", "Adaptation", "Full FT (baseline)"),
    ("loss_rmse_only_256res", "sng_pvc", "Loss", "RMSE only"),
    ("loss_rmse_h1_ssimfix_256res", "sng_pvc", "Loss", "RMSE + H1 + SSIM (0.15)"),
    ("lr_1e5_nossim_256res", "sng_pvc", "Learning rate", "LR $1\\times10^{-5}$"),
    ("loss_rmse_h1_128res", "sng_pvc", "Resolution", "Trained at $128^2$"),
    ("kl_1e7_256res", "sng_pvc", "Latent reg.", "KL $10^{-7}$"),
    ("kl_1e5_256res", "sng_pvc", "Latent reg.", "KL $10^{-5}$"),
    ("sds_stock_w1e4_256res", "sng_pvc", "Latent reg.", "SDS $10^{-4}$"),
    ("sds_stock_w1e2_256res", "sng_pvc", "Latent reg.", "SDS $10^{-2}$"),
    ("sds_stock_w1_256res", "sng_pvc", "Latent reg.", "SDS $1$"),
]
DIT_ARMS = ["loss_rmse_h1", "unfinetuned", "kl_1e7", "kl_1e5", "sds_stock_w1e4", "sds_stock_w1e2", "sds_stock_w1"]
LABEL = {a[0]: a[3] for a in VAE_ARMS}


def _run_dir(key: str, cluster: str) -> Path:
    return ROOT / "finetune_vae_outputs" / cluster / f"finetune_vae_ch6_{key}"


def _sem(x) -> float:
    x = np.asarray(x, dtype=float)
    return float(x.std(ddof=1) / np.sqrt(len(x)))


def _pct(v: float, base: float) -> str:
    return "--" if abs(v - base) < 1e-12 else f"{(v / base - 1) * 100:+.1f}\\%".replace("-", "$-$")


def _group_rows(rows, n_cols: int) -> list[str]:
    """Insert a \\midrule and a group caption row whenever the group changes."""
    out, prev = [], None
    for group, cells in rows:
        if group != prev:
            if prev is not None:
                out.append("\\midrule")
            out.append(f"\\multicolumn{{{n_cols}}}{{l}}{{\\textit{{{group}}}}} \\\\")
            prev = group
        out.append(" & ".join(cells) + " \\\\")
    return out


def _write(name: str, colspec: str, header: str, body: list[str], caption: str, label: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "% generated by scripts/thesis_tables.py -- do not edit by hand",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}",
        "\\toprule",
        header + " \\\\",
        "\\midrule",
        *body,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (OUT / name).write_text("\n".join(lines))
    print(f"wrote {OUT / name}")


def vae_test() -> None:
    reports = {}
    for key, cluster, _, _ in VAE_ARMS:
        p = _run_dir(key, cluster) / "test_eval_256.json"
        if p.exists():
            reports[key] = json.loads(p.read_text())
        else:
            print(f"vae_test: missing {p}")
    base = reports[BASELINE]["metrics"]["vrmse_chmean"]
    rows = []
    for key, _, group, label in VAE_ARMS:
        if key not in reports:
            continue
        m = reports[key]["metrics"]
        cells = [label, f"{m['vrmse']:.4f}",
                 f"{m['vrmse_chmean']:.4f} $\\pm$ {m['vrmse_chmean_sem']:.4f}",
                 _pct(m["vrmse_chmean"], base)] + [f"{m['vrmse_' + c]:.4f}" for c in CH]
        if key == BASELINE:
            cells = [f"\\textbf{{{c}}}" if i in (0, 2) else c for i, c in enumerate(cells)]
        rows.append((group, cells))
    _write(
        "vae_test.tex", "lrrrrrrr",
        "Arm & Pooled & Ch.\\ mean $\\pm$ SEM & $\\Delta$ & $\\rho$ & $m_x$ & $m_y$ & $p$",
        _group_rows(rows, 8),
        "VAE reconstruction VRMSE on the held-out test set (500 simulations, $256\\times256$). "
        "$\\Delta$ is the change of the channel-mean VRMSE relative to the baseline. "
        "Lower is better.",
        "tab:app_vae_test",
    )


def vae_val() -> None:
    test = {}
    for key, cluster, _, _ in VAE_ARMS:
        p = _run_dir(key, cluster) / "test_eval_256.json"
        if p.exists():
            test[key] = json.loads(p.read_text())["metrics"]["vrmse_chmean"]
    vals = {}
    for key, cluster, _, _ in VAE_ARMS:
        p = _run_dir(key, cluster) / "metrics" / "metrics.csv"
        if not p.exists():
            continue  # the unfinetuned reference was never trained, so it has no val row
        rows = [r for r in csv.DictReader(p.open()) if r.get("val_vrmse")]
        best = min(rows, key=lambda r: float(r["val_vrmse"]))
        chans = [float(best[f"val_vrmse_{c}"]) for c in CH]
        vals[key] = (int(best["epoch"]), float(best["val_vrmse"]), float(np.mean(chans)), chans)
    base_val, base_test = vals[BASELINE][2], test[BASELINE]
    rows = []
    for key, _, group, label in VAE_ARMS:
        if key not in vals:
            continue
        ep, pooled, chmean, chans = vals[key]
        cells = [label, str(ep), f"{pooled:.4f}", f"{chmean:.4f}", _pct(chmean, base_val),
                 _pct(test[key], base_test) if key in test else "n/a"] + [f"{v:.4f}" for v in chans]
        rows.append((group, cells))
    _write(
        "vae_val.tex", "lrrrrrrrrr",
        "Arm & Ep. & Pooled & Ch.\\ mean & $\\Delta_\\mathrm{val}$ & $\\Delta_\\mathrm{test}$ & $\\rho$ & $m_x$ & $m_y$ & $p$",
        _group_rows(rows, 10),
        "VAE reconstruction VRMSE on the validation split (500 simulations held out from the "
        "training file) at the checkpoint with the best validation VRMSE. "
        "$\\Delta_\\mathrm{val}$ and $\\Delta_\\mathrm{test}$ compare each arm with the baseline on the "
        "validation and test sets. The model trained at $128^2$ is validated on $128^2$ data.",
        "tab:app_vae_val",
    )


def dit() -> None:
    latest: dict[str, tuple[int, dict]] = {}
    for p in (ROOT / "logs" / "sng_pvc" / "eval_dit_vrmse").glob("*/vrmse_summary.json"):
        s = json.loads(p.read_text())
        if s.get("split") != "test" or s.get("n_samples") != 500:
            continue
        run = s["checkpoint"].split("/")[-3]  # shockwave_dit_ch6_<arm>
        arm = run.removeprefix("shockwave_dit_ch6_")
        job = int(p.parent.name)
        if arm in DIT_ARMS and (arm not in latest or job > latest[arm][0]):
            latest[arm] = (job, s)
    print("dit: evals used:", {a: latest[a][0] for a in DIT_ARMS if a in latest})
    base = latest["loss_rmse_h1"][1]["vae_dit_vrmse_chmean"]
    body = []
    for arm in DIT_ARMS:
        if arm not in latest:
            print(f"dit: no 500-sim test eval for {arm}")
            continue
        s = latest[arm][1]
        per = [np.mean(list(x["vae_dit_per_channel"].values())) for x in s["per_sample"]]
        label = LABEL[f"{arm}_256res"]
        cells = [label, f"{s['vae_only_vrmse_chmean']:.4f}",
                 f"{s['vae_dit_vrmse_chmean']:.4f} $\\pm$ {_sem(per):.4f}",
                 _pct(s["vae_dit_vrmse_chmean"], base)] + \
                [f"{s['vae_dit_vrmse_per_channel'][c]:.3f}" for c in CH] + [f"{s['latent_vrmse_mean']:.3f}"]
        if arm == "loss_rmse_h1":
            cells = [f"\\textbf{{{c}}}" if i in (0, 2) else c for i, c in enumerate(cells)]
        body.append(" & ".join(cells) + " \\\\")
    _write(
        "dit.tex", "lrrrrrrrr",
        "VAE & VAE only & VAE + DiT $\\pm$ SEM & $\\Delta$ & $\\rho$ & $m_x$ & $m_y$ & $p$ & Latent",
        body,
        "Channel-mean VRMSE of the VAE reconstruction alone and of the full pipeline "
        "(encode frame 0, DiT rollout, decode) on the test set (500 simulations), for a DiT "
        "trained for 8k steps on each VAE's latents. $\\Delta$ is relative to the baseline VAE; "
        "the per-channel columns are the VAE + DiT errors; \\emph{Latent} is the VRMSE of the "
        "rolled-out latent against the encoder's latent of the ground truth.",
        "tab:app_dit",
    )


if __name__ == "__main__":
    vae_test()
    vae_val()
    dit()
